acm-uic/acm-uic.github.io

docusaurus.config.js
- Update discord link.
- Add badges for discord, slack, github.
=> ✨ update community links and add badges

src/components/HomepageProfiles/HomepageProfiles.module.css, src/components/HomepageProfiles/HomepageProfiles.tsx, src/components/HomepageProfiles/index.ts, src/css/custom.css, src/pages/index.tsx
- Add officer and sysadmin profiles on homepage.
- Fix theme colors.
=> ✨ add officer, sysadmin profiles on homepage

.github/dependabot.yml, .github/labeler.yml, .github/labels.yml, .github/stale.yml, .github/workflows/ci.yml, .github/workflows/labeler.yml, .github/workflows/labels.yml, README.md
- Add GitHub actions to create labels, and auto assign labels to PRs.
- Add configuration for dependabot and stalebot.
- Add CI Badge to readme.
- Update gh actions in `ci.yml`.
=> 🚧 Add label actions + dependabot & stalebot

docs/Infrastructure/Servers/Bharat.md, docs/Infrastructure/Servers/Chase.md
* Adding basic info for Bharat
* Adding profile link for Chase
=> 📄 Adding info for Bharat and Chase servers

docs/Infrastructure/Overview.md
Added layout for the new main rack.
I labeled `acmapp` servers sequentially for the docs since they will be renamed that way soon™ anyways.
=> 📝 main rack layout

src/components/HomepageProfiles/HomepageProfiles.tsx
This PR updates the title of the board section.
=> Updated the header on the homepage to be more descriptive

src/pages/about.md
paragraph 2- "Bridge" -> means of communication
ACM -> ACM@UIC in paragraph 3
mentions documentation pages and blog and also GBM (also paragraph 3)
=> 📝 Update about page

docs/SIGs/sigsysadmin.md
I am adding a new SIG page for SIGSysAdmin.
This is just stub page for a demo.
=> Create sigsysadmin.md stub page

src/components/GoogleCalendarEmbed/GoogleCalendarEmbed.module.css, src/components/GoogleCalendarEmbed/GoogleCalendarEmbed.tsx, src/components/GoogleCalendarEmbed/index.ts, src/pages/index.module.css, src/pages/index.tsx
=> ✨ add gcal embed

blog/2021-08-22-welcome-back.md
Adding new blog post from Discord.
=> ✍️ Docs/new-semester-blog: Adding Christian's announcement from Discord

src/components/GoogleCalendarEmbed/GoogleCalendarEmbed.module.css
Just a quick fix the indenting in the CSS and to combine the margin rule.
=> 📝 Fixing indenting and combining css rules

.github/workflows/ci.yml
Fix bug where staging environments won't cleanup when PR was closed.
Added GH Actions job to cleanup stating environments.
=> 🐛 Add staging environment cleanup job

src/pages/index.module.css, src/pages/index.tsx
=> ✨ add join button + 🐛 fix button overflow

appConfig.js, docusaurus.config.js, src/components/DiscordLink/DiscordLink.tsx, src/components/DiscordLink/index.ts, src/components/DiscordRedirect/DiscordRedirect.tsx, src/components/DiscordRedirect/index.ts, src/components/EventsAgenda/EventsAgenda.tsx, src/components/GoogleCalendarEmbed/GoogleCalendarEmbed.tsx, src/config/index.ts, src/pages/discord.mdx, src/pages/join.mdx, tsconfig.json
- Add a discord redirect to make it easier to share discord server link with people. https://acm-uic.github.io/discord
- Convert app config to `js` so that it could be used by the docusaurus config too
=> ✨ add discord redirect

.vscode/settings.json, appConfig.js, docusaurus.config.js, src/components/SlackSignUpLink/SlackSignUpLink.tsx, src/components/SlackSignUpLink/index.ts, src/pages/contact.mdx, src/pages/join.mdx
- Add contact page
- Add `/contact` to footer nav
- Add `SlackSignUpLink` component
- Add slack workspace links to config.
=> 📝 Add Contact page

.vscode/settings.json, SIGs/overview.md, SIGs/siggame.md, SIGs/sigmath.md, SIGs/sigquantitativetrading.md, SIGs/sigsysadmin.md, SIGs/sigwebdev.md, appConfig.js, blog/2021-05-02-new-blog.md, blog/2021-08-22-welcome-back.md, blog/2021-08-29-Involvement-Fair.md, blog/2021-09-06-GBM-announcement.md, blog/authors.yml, docs/Infrastructure/Overview.md, docs/Infrastructure/Servers/Bharat.md, docs/Infrastructure/Servers/Chase.md, docs/Infrastructure/Servers/Overview.md, docs/Knowledge Base/Overview.md, docs/Knowledge Base/logos.md, docs/introduction.md, docusaurus.config.js, src/components/DiscordLink/DiscordLink.tsx, src/components/DiscordRedirect/DiscordRedirect.tsx
- Add slugs, tags, and descriptions to docs, and sigs
- Add `authors.yml` for blog post author config
- Fixed typos + update vscode dictionary
- Clean up docusaurus config
- Enable docs, sigs page show last update time, author
- Add blog description
=> 🔍 Polish and cleanup

SIGs/overview.md, SIGs/siggame.md, SIGs/sigmath.md, SIGs/sigquantitativetrading.md, SIGs/sigsysadmin.md, SIGs/sigwebdev.md
Fix a typo in the sigs frontmatter
=> 🐛 fix slugs of sigs/* pages

.github/CODEOWNERS
Add yarn.lock to codeowners file.
=> 🔍 Update CODEOWNERS

docusaurus.config.js
Signed-off-by: Soham S Gumaste <sohamg2@gmail.com>
Let me know what other orgs need to be added.
Also we probably should break up the docusaurus config into smaller json/js files according to feature.
=> 📝 Add links to other orgs in footer

LICENSE
=> ⚖️ Add LICENSE

.github/pull_request_template.md
=> 👮 Create pull_request_template.md

.github/CONTRIBUTING.md, README.md
Add contributing guide.
close #93
=> 📝 Add contributing guide

src/components/HomepageProfiles/HomepageProfiles.tsx, src/pages/officers.md
Add officers page with current officers and migrate officers page content.
close #123
=> 🚚 add officers page

blog/authors.yml, src/components/HomepageProfiles/HomepageProfiles.tsx
Update sysadmin profiles to include new sysadmin.
=> 📝  add sysadmin profile

src/pages/flourish-committee.md
Migrate Flourish committee page from old website
close #147
=> 🚚  migrate flourish committee page

CODE_OF_CONDUCT.md
Add code of conduct based on contributor covenant.
close #149
=> 👮 Create CODE_OF_CONDUCT.md

.devcontainer/devcontainer.json
run `yarn install` after creating devcontainer.
None
=> 🌟 install dependencies after creating devcontainer

docusaurus.config.js
- Add more typings to docusaurus config
- Navbar:
- Add links in about dropdown: about, officers, contact
- Footer:
- Add CS, COE UIC links
- Add Flourish link
- Add wiki link
- Add mail link
None
=> ✨ update nav

src/pages/officers.md
Add secretaries and SIG Leaders for 2021-2022 to officers.md
=> 📝 Add secretaries and SIG Leaders

docs/kb/Overview.md, docs/kb/_category_.yml, docs/kb/calendar-event-location-parsing.md, docs/kb/logos.md
Rename "Knowledge Base" to "kb" to resolve URLs without a space in the middle.
=> ✏️ rename kb folder

docusaurus.config.js, src/pages/contact.mdx
- Add /join to nav dropdown
- fix bold text on contact page
=> ✨ add join to nav dropdown, :bug: fix bold text

SIGs/Active/sigsysadmin.mdx
Due to an Google Drive change, the URL has been updated. Link has been fixed to allow anonymous users.
N/A
=> Updating Google Drive link

SIGs/Active/sigsysadmin.mdx
Adding all the presentations for the semester.
N/A
=> 🛠️Adding SIGSysAdmin presentations for Fall 2021

SIGs/Active/sigmath.md, SIGs/Active/sigsysadmin.mdx, SIGs/Inactive/lug-web/2013-2014-topic-archives.md, SIGs/Inactive/lug-web/introduction.md, SIGs/Inactive/sigai.md, SIGs/Inactive/sigandroid.md, SIGs/Inactive/sigblockchain.md, SIGs/Inactive/sighcl.md, SIGs/Inactive/sigmicro.md, SIGs/Inactive/sigopen.md, SIGs/Inactive/sigwindows.md
Update paths after organizing media files
Migrate SIGs:
- sig windows
- sig ai
- sig blockchain
- sig math
- sig android
- sig hcl
closes #140
closes #133
closes #132
closes #130
closes #129
closes #128
=> 🚚 migrate sigs

package.json, yarn.lock
Bump docusaurus packages to 2.0.0-beta.14
=> ⬆️ bump docusaurus packages to 2.0.0-beta.14

.github/dependabot.yml, .github/workflows/dependabot.yml
- Enable auto merge for dependabot PRs
- Use dependabot to update version requirements along with lock files
- Ignore major version updates for dependabot updates
- Add commit message prefix for dependabot PRs
=> ⚙️  dependabot config update

package.json, yarn.lock
bump docusaurus to 2.0.0-beta.16
=> ⬆️ bump docusaurus to 2.0.0-beta.16

SIGs/Active/sigsysadmin.mdx
Updated the Sysadmin list for ACM.
=> Updating Sysadmin Admins

SIGs/Active/sigsysadmin.mdx
=> ✏️ Update sysadmin status

SIGs/Active/siggame.mdx
Updated SIG Game page to have current weekday and time information for meetings.
=> 🎮 Update SIG Game meeting weekday and time

package.json, yarn.lock
bump docusaurus to 2.0.0-beta.17
=> ⬆️ bump docusaurus to 2.0.0-beta.17

SIGs/Active/sigsysadmin.mdx
This PR adds the slide for the Spring 2022 semester.
N/A
=> 🌼🌷🌻Adding SIGSysAdmin slides for Spring 2022

package.json, yarn.lock
bump docusaurus to 2.0.0-beta.20
=> :arrow_up: bump docusaurus to 2.0.0-beta.20

blog/authors.yml, src/components/HomepageProfiles/HomepageProfiles.tsx, src/pages/officers.md
=> 🤓 update officers

.github/workflows/ci.yml, package.json, src/components/DiscordLink/DiscordLink.tsx, src/components/SlackSignUpLink/SlackSignUpLink.tsx, src/components/YouTubeLink/YouTubeLink.tsx, yarn.lock
⬆️ bump docusaurus to 2.0.0-beta.21
⬆️ use node 18 for CI
N/A
=> ⬆️ bump docusaurus to 2.0.0-beta.21

docs/kb/calendar-event-location-parsing.md
Update wiki link for discord event sync bot.
=> 📝 Update wiki link for discord event sync bot.

.github/CODEOWNERS
=> 🐛 fix codeowners typo

docs/Infrastructure/Overview.md, docs/Infrastructure/Servers/Lee.md, docs/kb/Linux/_category_.yml, docs/kb/Linux/proxmox-raid-setup.md
Adding basic info for server Lee. Writing Proxmox documentation for RAID setup and notes.
- Additional testing on the actual server may be needed. Documentation may change later.
- This is related to acm-uic/IaC#15.
=> Lee server documentation

docs/Infrastructure/Servers/Lee.md
Follow up to #361.
Related to acm-uic/IaC#15
=> Update Lee documentation to include ZFS update

package.json, yarn.lock
=> ⬆️ bump docusaurus 2.0.0-beta.22

package.json, yarn.lock
⬆️ bump docusaurus to 2.0.0-rc.1
=> ⬆️ bump docusaurus to 2.0.0-rc.1

package.json, yarn.lock
=> ⬆️ bump docusaurus to 2.0.1

package.json, yarn.lock
=> ⬆️ bump docusaurus to 2.1.0

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Add bug report and feature request issue templates
resolves #94
=> ⚙️ Add issue templates

.github/dependabot.yml
run dependabot updates on saturday mornings
=> ⚙️ run dependabot updates on saturday mornings

src/components/EventsAgenda/EventsAgenda.tsx, src/pages/index.tsx, src/util/getEvents.ts
- fix issue where 9 events were hard coded into api request
- fix cache keys for swr requests
=> 🐛 fix issue where 9 events were hard coded into api request

src/pages/index.tsx
#495 accidentally changed event count to 20.
=> 🐛 show 9 events on homepage

package.json, yarn.lock
=> ⬆️bump docusaurus to 2.2.0

docs/Infrastructure/Overview.md
This PR updates the description for a server in the main server rack.
N/A
=> Update description for mislabeled server

.vscode/extensions.json
`silvenon.mdx` is deprecated. Updated recommended extensions.
=> 🔧 update recommended mdx extension

src/components/EventsAgenda/EventsAgenda.tsx
Filter private events form home page agenda
=> ✨ filter private events

src/components/HomepageProfiles/HomepageProfiles.tsx, src/pages/officers.md
=> ⬆️ update officers

blog/2023-01-23-GBM-announcement.md, blog/authors.yml
* Adding new announcement from Discord. (https://discord.com/channels/652006495675875359/652006847334842378/1067150040298180708)
=> 📢 GBM Announcement for Spring 2023

SIGs/Active/sigsysadmin.mdx
This PR adds the presentation links for SIGSysAdmin up until 1/30/2023.
=> 💻Adding SIGSysAdmin presentations up until the first meeting of Spring 2023

yarn.lock
bump indirect deps in lockfile.
=> ⬆️ bump indirect deps

.github/workflows/ci.yml
I came across a new button in the pages deployment settings.
=> 👀 use new pages actions

package.json, yarn.lock
=> ⬆️ bump docusaurus to 2.3.1

.github/workflows/ci.yml, .github/workflows/typesense-scraper-config.json, .github/workflows/typesense-scraper.yml, .vscode/settings.json, docusaurus.config.js, package.json, yarn.lock
=> 🔍 add typesense search

.github/workflows/typesense-scraper.yml
fixup path in scraper workflow
=> 🚨 fixup path in scraper workflow

docusaurus.config.js
add appropriate aria-labels to external links in the site footer.
=> 🐛 fix footer links aria labels

package.json, yarn.lock
=> ⬆️ bump docusaurus to 2.4.0

src/components/HomepageProfiles/HomepageProfiles.tsx, src/pages/officers.md
=> 📝 update 2023 officers

SIGs/Active/sigsysadmin.mdx
- Adding link to last Jeopardy meeting for SIGSysAdmin.
- Updating schedule info.
- Adding page description to frontmatter for Open Graph metadata.
=> 🧑‍💻 SIGSysAdmin Spring 2023 semester end updates

tf/main.tf
=> ⬆️ bump terraform to 1.4.6

.github/workflows/ci.yml
=> 🐛 only run tf plan on PRs

README.md
This fixes a minor spelling mistakes... but really... we just want to run Terraform. 🙃
N/A
=> 🪄 Update README.md

.github/workflows/ci.yml, tf/main.tf, tf/typesense.tf
get typesense api key, host from job outputs
#664
=> 🐛 get typesense api key, host from job outputs

.github/workflows/ci.yml
get typesense api key, host from job outputs fixup
#664
=> 🐛 get typesense api key, host from job outputs fixup

package.json, yarn.lock
=> ⬆️ bump docusaurus to 2.4.1

.github/workflows/ci.yml
- run scraper job after deployment
- fixup scraper job command
=> 🐛 run scraper job fixup

src/components/HomepageProfiles/HomepageProfiles.tsx
This fixes the broken image link for one of the current officers.
N/A
=> 🩹 Fix HomepageProfiles images

.github/workflows/ci.yml
Bump `typesense/docsearch-scraper` image to 0.7.0
=> ⬆️ Bump typesense/docsearch-scraper image to 0.7.0

.github/workflows/ci.yml, src/pages/index.tsx
Disable concurrency for terraform CI steps to avoid state lock conflicts.
=> 👷 terraform apply/plan disable concurrency

.github/workflows/drift.yml
Add scheduled terraform drift check
=> 🤖 Add scheduled terraform drift check

docusaurus.config.js
Add plausible analytics 🕵️
https://plausible.acmuic.org/acm.cs.uic.edu/
=> 🕵️ plausible analytics

.github/workflows/labeler.yml
Reverts acm-uic/acm-uic.github.io#862
=> Revert ":arrow_up: Bump actions/labeler from 4 to 5"

package.json, yarn.lock
bump docusaurus-theme-search-typesense to 0.22.0-1
=> ⬆️ bump docusaurus-theme-search-typesense to 0.22.0-1

SIGs/Active/siggame.mdx, SIGs/Active/sigindiedev.md, SIGs/Active/sigsysadmin.mdx, SIGs/Active/sigsystems.md, SIGs/Active/sigvr.md
This updates page contents for:
- SIGSysAdmin
- SIG Indie Dev
- SIG Systems
- SIG VR
- SIG Game
=> SIG Page Updates

SIGs/Active/sigsysadmin.mdx
Adding the rest of the presentations for the semester.
=> SIGSysAdmin Page Update
