docusaurus.config.js
Enabling the prefer color scheme media query to respect system color schemes.
Documentation: https://docusaurus.io/docs/api/themes/configuration
=> 🔆 Enable color scheme media query

src/components/GoogleCalendarEmbed/GoogleCalendarEmbed.tsx
This PR updates the gcal component to not specify the timezone. (I was wondering why the times looked a bit off... haha.
Without this parameter, the Google calendar will use the user's current timezone.
* I was able to locally spin up a dev server and view the embedded calendar iframe on the site.
* Loading the iframe URL directly also displayed the correct time for me.
=> ⌚ Update GoogleCalendarEmbed.tsx to use local timezone

docs/SIGs/siggame.md, docs/SIGs/sigmath.md, docs/SIGs/sigquantitativetrading.md, docs/SIGs/sigsysadmin.md, docs/SIGs/sigwebdev.md
Adding stub notes of most SIG pages.
* This was tested locally using `yarn build`.
=> 🌟Adding base info for previous SIGs. 

docusaurus.config.js
Site title in the navbar next to the logo seems redundant. We still have it in the `alt` text of the logo incase it does not render.
before: ![image](https://user-images.githubusercontent.com/5100938/132164917-46cd02a9-1913-4916-8659-41bc696d1b0b.png)
after: ![image](https://user-images.githubusercontent.com/5100938/132170101-279f3856-5adc-47d7-84b1-833b12f01af0.png)
=> 🔥 remove redundant title from navbar

src/pages/join.md
This PR adds a simple link to the backup ACM Membership form, in the event that the newer form is not ready yet.
=> 📜 Adding temporary ACM membership form via Google Forms

.eslintrc.js, appConfig.js, babel.config.js, docusaurus.config.js, src/components/DiscordLink/DiscordLink.tsx, src/components/DiscordRedirect/DiscordRedirect.tsx, src/components/EventsAgenda/EventsAgenda.tsx, src/components/GoogleCalendarEmbed/GoogleCalendarEmbed.tsx
- Fixed bug where `appConfig` import in `docusaurus.config.js` was undefined.
- Add typechecking to `.js` config files
- Use navbar discord href from config file.
=> 🩹 use discord server link from `appConfig` + 🏷 typecheck `.js` config files

src/components/EventsAgenda/EventsAgenda.tsx
Signed-off-by: Soham S Gumaste <sgumas2@uic.edu>
This is just a personal gripe I thought the link to the full ACM calendar should be more prominent.
I tried to get the button to be centered with the cards but its like 3-5px off for some reason I cant find even with inspect element.
=> 🌟 Make calendar button more prominent

.devcontainer/devcontainer.json
GitHub codespaces do not fetch the submodules by default. This change adds a command to get the submodules after creating the container. This should improve the developer experience when creating new codespace instances.
=> ⚙️ add devcontainer config to get submodules after creating instance

.github/workflows/ci.yml
Update workflow to use [caching feature in setup-node](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies).
=> ⚡ Update workflows to use setup-node cache

.eslintrc.js, src/components/EventsAgenda/EventsAgenda.tsx, src/util/getDiscordWidgetApi.ts, src/util/getEvents.ts
- Add logic to parse event location to show Discord invite link when location starts with "Discord Stage:" or "Discord Voice:".
- Show 9 events (instead of 10). Makes a 3x3 grid on desktop/tablet viewports.
- Bump media submodule to use Discord logo.
=> ✨  add discord location parsing to events agenda

src/pages/join.mdx
Fix bold text on /join page.
before:
after:
=> 🐛 fix bold text on /join page

docs/Knowledge Base/calendar-event-location-parsing.md, docs/Knowledge Base/calendar-event-location.md
- Add documentation about calendar event location parsing.
- Related PR: #117 
- Preview link: <https://brave-sea-0f799c410-154.centralus.azurestaticapps.net/docs/kb/calendar-event-location-parsing>
None
=> 📝 add discord event parsing docs

src/pages/contact.mdx
Fix line breaks in address information on /contact page.
before:
after:
=> Fix line breaks in /contact

src/components/EventsAgenda/EventsAgenda.module.css, src/components/EventsAgenda/EventsAgenda.tsx
Fix EventsAgenda component css. Discord icon was too large.
before:
after:
=> 🐛 fix discord icon styles

src/components/EventsAgenda/EventsAgenda.module.css, src/components/EventsAgenda/EventsAgenda.tsx, src/components/Shimmer/ShimmerLine.module.css, src/components/Shimmer/ShimmerLine.tsx, src/components/Shimmer/index.ts, src/util/getEvents.ts
Add empty event items to reduce layout reflow when calendar events are loaded.
Add error, loading, empty state for calendar events.
| | Before | After |
| --- | ------ | ------|
|loading (gif) |![events-loading-before](https://user-images.githubusercontent.com/5100938/155032546-096073d0-c0c7-4660-ad2b-3f667b37c35e.gif) |![events-loading-after](https://user-images.githubusercontent.com/5100938/155032685-dfbdf257-53e5-414c-a21d-a7558a60da88.gif) |
|error | N/A | ![error-events-after](https://user-images.githubusercontent.com/5100938/155032182-ded9a413-159e-49e9-afed-ee0fc01ebdad.png)
|empty | ![image](https://user-images.githubusercontent.com/5100938/155032732-56a7d568-1767-481e-a46e-857861d17779.png) | ![no-events-after](https://user-images.githubusercontent.com/5100938/155032183-2759909c-a …
=> ✨  add loading/empty/error state for events agenda component

docusaurus.config.js
Don't show updated date and author on docs. This date can be misleading because it is based on the latest build and not when the file was updated.
=> don't show updated date and author

SIGs/Active/sigsysadmin.mdx
Updates the SIG SysAdmin page with more presentation information.
N/A
=> Adding SIG SysAdmin presentations since October 3, 2022

src/components/EventsAgenda/EventsAgenda.tsx, src/components/Shimmer/ShimmerLine.module.css, src/components/Shimmer/ShimmerLine.tsx
stop shimmering animation when events fail to load
it was distracting to see the shimmer animation in the background of the events error state.
=> ✨ stop shimmering animation when events fail to load

tf/.terraform.lock.hcl, tf/main.tf
Reverts acm-uic/acm-uic.github.io#740
=> Revert ":arrow_up: Bump hashicorp/azurerm from 3.64.0 to 3.65.0 in /tf"

blog/2023-08-31-GBM-announcement.md, blog/authors.yml
Adding the Fall 2023 GBM blog post
N/A
=> 🗒️Adding Fall 2023 GBM blog post

.github/workflows/ci.yml
=> 🚑 trigger pr terraform plan

src/components/HomepageProfiles/HomepageProfiles.tsx
Added myself as a sysadmin :3 Also, the `officers.md` page has historically had Sysadmin/Webmaster listed in the table, is that no longer a thing?
=> add myself as a sysadmin
